name: Lawlessness

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        variant: [normal, ksu]
    name: 编译内核 (${{ matrix.variant }})
    steps:
    - name: 1. 检出云端内核源码
      uses: actions/checkout@v4
      with:
        ref: master
    - name: 2. 初始化编译环境
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf libelf-dev libssl-dev lzop rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
    - name: 2.5 检查/恢复 Clang 缓存
      id: cache-clang
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/clang
        key: aosp-clang-linux-x86
    - name: 3 集成KSU
      if: matrix.variant != 'normal'
      run: |
        cd $GITHUB_WORKSPACE
        curl -LSs "https://raw.githubusercontent.com/ReSukiSU/ReSukiSU/main/kernel/setup.sh" | bash  
    - name: 4. 秘术：超神魔改赋能
      if: matrix.variant != 'normal'
      run: |
        cd $GITHUB_WORKSPACE
        echo "开始为RE-SUKISU赋能"
        cp legendary.c KernelSU/kernel/selinux/rules.c
        echo "赋能后检查是否赋能成功"
        cat KernelSU/kernel/selinux/rules.c | grep "feimengxinren"
        STATUS=$?
        if [ $STATUS -eq 0 ]; then
          echo "已检测到特定标志，赋能成功！"
          echo "已打上特定标签标记完全体版本"
          sed -i 's/-dirty/-pro_max/g' KernelSU/kernel/Kbuild
        else
          echo "未检测到特定标志，赋能失败！"
        fi
    - name: 4.5 打上若干补丁 + 移除 KSU 配置
      if: matrix.variant == 'normal'
      run: |
        cd $GITHUB_WORKSPACE
        DEFCONFIG_PATH="arch/arm64/configs/vendor/kona-perf_defconfig"
        echo "移除KSU配置"
        sed -i '/CONFIG_KSU/d' $DEFCONFIG_PATH
        sed -i '/CONFIG_KSU_MANUAL_HOOK/d' $DEFCONFIG_PATH
        echo "在Makefile与Kconfig中移除KSU相关代码"
        sed -i '/obj-\$(CONFIG_KSU) += kernelsu\//d' drivers/Makefile
        sed -i '/source "drivers\/kernelsu\/Kconfig"/d' drivers/Kconfig
        echo "关闭本地源码完整性校验"
        git diff --name-only | xargs -I {} git update-index --assume-unchanged "{}"
    - name: 5. 配置环境&开始编译
      run: |
        cd $GITHUB_WORKSPACE
        if [ -f "${{ github.workspace }}/clang/bin/clang" ]; then
          ${{ github.workspace }}/clang/bin/clang --version
        fi
        export KBUILD_BUILD_USER="kleaf"
        export KBUILD_BUILD_HOST="build-host"
        export LOCALVERSION=""
        export LOCALVERSION_AUTO=y
        export KBUILD_BUILD_TIMESTAMP="$(TZ="Asia/Shanghai" date +"%a %b %d %H:%M:%S CST %Y")"
        export ARCH=arm64
        export SUBARCH=arm64
        export PATH=$GITHUB_WORKSPACE/clang/bin:$PATH
        export CC=clang
        export CROSS_COMPILE=aarch64-linux-gnu-
        export LLVM=1 
        export LLVM_IAS=1
        make O=out vendor/kona-perf_defconfig vendor/xiaomi/munch.config
        make O=out -j$(nproc --all) Image.gz
    - name: 6. 上传 Image.gz
      uses: actions/upload-artifact@v4
      with:
        name: Munch-Image-${{ matrix.variant }}
        path: out/arch/arm64/boot/Image.gz