name: clang update & cache KeepAlive
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  refresh-cache:
    runs-on: ubuntu-latest
    steps:
    - name: 1. get latest clang ver
      id: get_version
      run: |
        LATEST_VER=$(curl -s "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86" | grep -o 'clang-r[0-9]*[a-z]*' | tail -n 1)
        echo "latest ver: $LATEST_VER"
    - name: 2. try get clang on cache storage
      id: cache-clang
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/clang
        key: aosp-clang-linux-x86
    - name: 3. version comparison
      run: |
        LATEST_VER=$(curl -s "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86" | grep -o 'clang-r[0-9]*[a-z]*' | tail -n 1)
        NEED_DOWNLOAD="false"
        if [ "${{ steps.cache-clang.outputs.cache-hit }}" != 'true' ]; then
          echo "cache is null ! exec download now"
          NEED_DOWNLOAD="true"
        else
          LOCAL_VER=$(${{ github.workspace }}/clang/bin/clang --version | grep -o 'based on r[0-9]*' | grep -o 'r[0-9]*')
          WEB_VER=$(echo "$LATEST_VER" | grep -o 'r[0-9]*')     
          echo "local cache ver: r${LOCAL_VER}，latest ver: r${LATEST_VER}"
          if [ "$LOCAL_VER" != "$LATEST_VER" ]; then
            echo "new ver detected"
            rm -rf ${{ github.workspace }}/clang
            NEED_DOWNLOAD="true"
          else
            echo "already up-to-date no actions"
            ${{ github.workspace }}/clang/bin/clang --version
          fi
        fi
        if [ "$NEED_DOWNLOAD" = "true" ]; then
          echo "downloading : $LATEST_VER"
          mkdir -p ${{ github.workspace }}/clang
          cd ${{ github.workspace }}/clang
          wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/mirror-goog-main-llvm-toolchain-source/$LATEST_VER.tar.gz -O clang.tar.gz
          tar -xf clang.tar.gz
          echo "upgrade complete"
        fi